### ISSUE TITLE
Can not get memory info of PID 0

### ISSUE THREAD

**Issue by loquat** [thetrik/Vb64BitDllUsage#1]
Msgbox: GetProcessMemoryInfo64 failed

**Comment by thetrik** [comment]
https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-openprocess

> If the specified process is the System Idle Process (0x00000000), the function fails and the last error code is ERROR_INVALID_PARAMETER.

If you need to get such information you could use **NtQuerySystemInformation** with **SystemProcessInformation** class (Task manager uses such approach)

**Comment by loquat** [comment]
thanks, that is very kind of you.
